eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

server:
  port: 8070

spring:
  application:
    name: schools
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888  # Config server URL
  config:
    import: optional:configserver:http://localhost:8888  # Config server is optional
  datasource:
  driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: Astag@123
  jpa:
    hibernate:
      ddl-auto: create
      database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Fix students-url property placement
application:
  config:
    students-url: http://localhost:8090/api/students
